### ISSUE TITLE
Error while bringing up the go application "changes are not synced and port is not matching with the server file code"

### ISSUE THREAD

**Issue by Kushan-** [mikemadisonweb/go-autoreload-example#1]
Directory structure
test
 |-app
     |--app_settings
          |---log_wrapper.go
     |--root
          |---entrypoint.sh
     |--Dockerfile
     |--main.go
 |-.env
 |-docker-compose.yaml

Dockerfile looks like :- 
```
FROM golang:1.9-alpine
COPY ./root /
COPY ./app_settings/ /go/src/app_settings/
RUN apk add --no-cache ca-certificates \
        dpkg \
        gcc \
        git \
        musl-dev \
        bash

ENV GOPATH /go
ENV PATH $GOPATH/bin:/usr/local/go/bin:$PATH

RUN mkdir -p "$GOPATH/src" "$GOPATH/bin" \
    && chmod -R 777 "$GOPATH" \
    && chmod +x /entrypoint.sh

# RUN go get github.com/tockins/realize #<---placing this code giving me the error ERROR: Service 'app' #failed to build: The command '/bin/sh -c go install -v ./...' returned a non-zero code: 1
RUN go get -d -v ./...

RUN go install -v ./...
RUN go get github.com/tockins/realize #works fine here but when i output realize.yaml which is #created in root directory gives me output mentioned below (which is same as your common app)
WORKDIR $GOPATH
ENTRYPOINT ["/entrypoint.sh"]
EXPOSE 8080
CMD ["realize", "start"]
```
docker-compose.yaml
```
version: '3'
services:
  app:
    container_name: "app"
    build: "./app/"
    volumes:
      - ".:${GO_PROJECT_DIR}"
    ports:
      - "8080:8080"
    environment:
      GO_WORK_DIR: "${GO_PROJECT_DIR}/app"
```

main.go
```package main


import (
	l "app_settings/log_wrapper"
	"fmt"
	"io/ioutil"
	"os"

	"github.com/qiangxue/fasthttp-routing"
	"github.com/valyala/fasthttp"
)

func main() {

	l.Init(ioutil.Discard, os.Stdout, os.Stdout, os.Stderr)

	l.Trace.Println("I have something standard to say")
	l.Info.Println("Special Information")
	l.Warning.Println("There is something you need to know about")
	l.Error.Println("Something has failed")

	router := routing.New()

	router.Get("/", func(c *routing.Context) error {
		fmt.Fprintf(c, "UP, and running with golang app!")
		l.Info.Println("fasthttp, Hello, Go!")
		return nil
	})

	panic(fasthttp.ListenAndServe(":8080", router.HandleRequest))
}
```
entrypoint.sh

```
#!/usr/bin/env bash
GO_WORK_DIR=${GO_WORK_DIR:-$GOPATH/src}
cd ${GO_WORK_DIR}
cd root && ls -a && exec "$@"
```
.realize.yaml output
```app    | settings:
app    |   legacy:
app    |     force: false
app    |     interval: 0s
app    | server:
app    |   status: false
app    |   open: false
app    |   port: 5002
app    |   host: localhost
app    | schema:
app    | - name: app
app    |   path: .
app    |   commands:
app    |     run:
app    |       status: true
app    |   watcher:
app    |     paths:
app    |     - /
app    |     - ./../common
app    |     extensions:
app    |     - go
app    |     - html
app    |     - css
app    |     - js
app    |     - yaml
```

output of the above code base
`[22:33:04][ROOT] : Watching 0 file/s 1 folder/s`
but the changes made in main.go is not reflected, furthermore there seems to be some issue with the post as well. 
I am still a newbie with go, try to bring up my own go test app. Any help would be appreciated. thanks!

**Comment by mikemadisonweb** [comment]
[test.zip](https://github.com/mikemadisonweb/go-autoreload-example/files/3455836/test.zip)
Hi, please find the working version of your app with autoreload in the attachment. I don't know what was wrong with your example, you need to figure it out by yourself. One difference is that i have commented out `app_settings/log_wrapper` as i didn't have it.
Also, i don't know which IDE are you using, but keep in mind that autoreaload watch for changes in the files, so changes need to be saved in order autoreload to fire. My Goland saves the file automatically when i leave the window, but not sure about other IDEs.

**Comment by Kushan-** [comment]
hey, thanks for the working setup, app_settings has flies like logging.go and driver.go so that i can use then from other apps as well. Please find the attachment of the directory structure. I am using visual studio/sublime.
While running the project below, i am trying to get and install files in app_setting and getting error.
One question which is popping up is why port in realize.yaml is 5*** while our app is listening to 8181?
[github_test.zip](https://github.com/mikemadisonweb/go-autoreload-example/files/3458825/github_test.zip)

**Comment by mikemadisonweb** [comment]
Hey, this 5002 is an internal realize server port. I understand the idea they put behind it, but it never worked for me(empty response). 
Actually, you can remove the whole `server` section from the .realize.yaml

**Comment by Kushan-** [comment]
Ah i see, thanks for the explanation. Wondering if you can spin up the provided file with the current setup, where i am same error as stated in the initial thread.(uploaded the same file again for convince )
[github_test.zip](https://github.com/mikemadisonweb/go-autoreload-example/files/3463194/github_test.zip)

**Comment by mikemadisonweb** [comment]
[autoreload.zip](https://github.com/mikemadisonweb/go-autoreload-example/files/3466788/autoreload.zip)
I don't see any error message in the initial post. I have modified your example in order for it to work, but that would be the last time:)
It should be unpacked to {YOUR_GOPATH}/src.
Recommendations for you:
1) Don't deal with dependency hell by your own, use tools like [Glide](https://glide.sh/).
2) Learn how to [structure the project folders](https://golang.org/doc/code.html).

**Comment by Kushan-** [comment]
thanks!
